version: '3.9'

services:
#Contenedor del productor
  python:
    build:
      context: ./productor
      dockerfile: Dockerfile
    depends_on:
      - broker
    volumes:
      - ./productor/scripts:/scripts 
    command: python productor.py
    networks:
      - link
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  #Contenedor de la transmisión
  python-transmision:
    build:
      context: ./python-transmision
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "7077:7077"
    depends_on:
      - broker
      - rtsp-server
    volumes:
      - ./python-transmision/scripts:/scripts
    command: python transmision.py
    networks:
      - link
  
  #Contenedor de las alertas
  python-alertas:
    build:
      context: ./python-alertas
      dockerfile: Dockerfile
    depends_on:
      - broker
    volumes:
      - ./python-alertas/scripts:/scripts
    networks:
      - link

  #Contenedor para Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - link
  #Contenedor para el broker de Kafka
  broker:
    image: confluentinc/cp-kafka:7.6.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_LOG_RETENTION_MS: "300000"
    networks:
      - link
  #Contenedor que hostea el servidor RTSP para la transmisión del stream con cajas de detección
  rtsp-server:
    image: bluenviron/mediamtx:latest
    container_name: rtsp-server
    restart: unless-stopped
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    networks:
      - link 

  #Contenedor necesario para que Grafana pueda dar visualización de streams RTSP
  go2rtc:
    image: alexxit/go2rtc
    container_name: go2rtc
    ports:
      - "1984:1984" 
    volumes:
      - ./go2rtc-config/go2rtc.yaml:/config/go2rtc.yaml
    restart: unless-stopped
    networks:
      - link 

  #Contenedor de InfluxDB, la configuración se hace mediante el archivo 'variables.env' en la carpeta 'conf'
  influxdb:
      image: influxdb:latest
      container_name: influxdb
      ports:
          - "8086:8086"
      depends_on:
          - python-alertas
          - grafana
      env_file: "./conf/variables.env"
      networks:
        - link
      volumes:
          - ./data/influxdb/:/var/lib/influxdb

  #Contenedor de Grafana
  grafana:
    build: './grafana'
    container_name: grafana
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana/data
    ports:
      - "3000:3000" 
    environment:
      - GF_INSTALL_PLUGINS=innius-video-panel
    networks:
      - link 
volumes:
  grafana_data: {}
 

networks:
  link:
    driver: bridge